### PR TITLE
Display package name/versions in header and html title

### PR DESCRIPTION
**Pull request by greg-rychlewski**
Closes https://github.com/hexpm/diff/issues/77

Example:

Screen Shot 2022-04-26 at 11 06 53 PM

### CODE REVIEW

**Comment by greg-rychlewski** [comment]
it might look nicer to put the versions under the package name

Screen Shot 2022-04-26 at 11 21 47 PM

Screen Shot 2022-04-26 at 11 23 34 PM

**Comment by ericmj** [comment]
Looks great. Can you change the header to include the versions: `ecto 3.7.0..3.7.2 | hexdiff`?

**Comment by greg-rychlewski** [comment]
Thanks for the review. Here's what it looks like now:

Screen Shot 2022-04-27 at 9 09 40 AM

**Comment by wojtekmach** [comment]
Thank you!

**Comment by thbar** [comment]
Thanks @greg-rychlewski for implementing this! Much appreciated.

**Pull request merged**
