### PR TITLE
Fix error pages

### PR DESCRIPTION
**Pull request by ericmj**
This makes the error pages a bit more consistent by showing them in all contexts and with a layout.

### CODE REVIEW

**Review by wojtekmach — APPROVED** [review]
Nice!

**Review by joladev — APPROVED** [review]
🎉

**Review by supersimple — APPROVED** [review]
that yarn.lock is making for a big diff :/

**Comment by ericmj** [comment]
> that yarn.lock is making for a big diff :/

Yeah, looks like they updated URLs, did formatting changes, and added checksums 😓

**Pull request merged**
